[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  node_bundler = "esbuild"
  included_files = ["data/artworks.json"]
